# Auto-generated by setup.sh — API proxy endpoints for landing page widgets
# Keys are injected here so they never reach the browser.
#
# Because these requests carry admin API keys, only the exact read-only
# endpoints the landing page uses are exposed, and only for GET/HEAD.
# Anything else under /api/ falls through to the 404 in nginx.conf.
#
# Upstreams are variables so nginx starts even if a service is down.
# When proxy_pass contains variables and a URI, nginx sends that URI as-is,
# so each location spells out the full upstream URL including $args.

# qBittorrent (no key — nginx's fixed IP is on qBittorrent's auth whitelist)
location = /api/qbt/torrents/info {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_qbt http://qbittorrent:8081/api/v2/torrents/info$is_args$args;
    proxy_pass $upstream_api_qbt;
    proxy_set_header Host qbittorrent:8081;
    proxy_set_header Referer http://qbittorrent:8081;
    proxy_set_header Origin http://qbittorrent:8081;
}
location = /api/qbt/sync/maindata {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_qbt http://qbittorrent:8081/api/v2/sync/maindata$is_args$args;
    proxy_pass $upstream_api_qbt;
    proxy_set_header Host qbittorrent:8081;
    proxy_set_header Referer http://qbittorrent:8081;
    proxy_set_header Origin http://qbittorrent:8081;
}

# Sonarr
location = /api/sonarr/calendar {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_sonarr http://sonarr:8989/api/v3/calendar$is_args$args;
    proxy_pass $upstream_api_sonarr;
    proxy_set_header X-Api-Key "{{SONARR_KEY}}";
}

# Sonarr Anime
location = /api/sonarr-anime/calendar {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_sonarr_anime http://sonarr-anime:8989/api/v3/calendar$is_args$args;
    proxy_pass $upstream_api_sonarr_anime;
    proxy_set_header X-Api-Key "{{SONARR_ANIME_KEY}}";
}

# Radarr
location = /api/radarr/calendar {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_radarr http://radarr:7878/api/v3/calendar$is_args$args;
    proxy_pass $upstream_api_radarr;
    proxy_set_header X-Api-Key "{{RADARR_KEY}}";
}

# Jellyfin
location = /api/jellyfin/Items {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_jellyfin http://jellyfin:8096/Items$is_args$args;
    proxy_pass $upstream_api_jellyfin;
    proxy_set_header X-Emby-Token "{{JELLYFIN_API_KEY}}";
}

# Jellyseerr
location = /api/jellyseerr/request {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_jellyseerr http://jellyseerr:5055/api/v1/request$is_args$args;
    proxy_pass $upstream_api_jellyseerr;
    proxy_set_header X-Api-Key "{{JELLYSEERR_KEY}}";
}

# SABnzbd — its API is one URL with a mode parameter, so only the queue and
# history modes are allowed and the query string is rebuilt rather than
# forwarded (the client can't smuggle in its own mode or apikey).
location = /api/sabnzbd/ {
    limit_except GET { deny all; }
    limit_req zone=api burst=50 nodelay;
    if ($arg_mode !~ ^(queue|history)$) {
        return 403;
    }
    if ($arg_limit !~ ^[0-9]*$) {
        return 400;
    }
    set $upstream_api_sabnzbd "http://sabnzbd:8080/api?apikey={{SABNZBD_KEY}}&output=json&mode=$arg_mode&limit=$arg_limit";
    proxy_pass $upstream_api_sabnzbd;
}
