# Auto-generated by setup.sh — API proxy endpoints for landing page widgets
# Keys are injected here so they never reach the browser.
# Rate-limited to prevent abuse.
# Uses nginx variables + rewrite for upstream resolution so nginx starts even if a service is down.
# IMPORTANT: set must come BEFORE rewrite ... break; (both are rewrite-module directives)

# qBittorrent
location /api/qbt/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_qbt http://qbittorrent:8081;
    rewrite ^/api/qbt/(.*)$ /api/v2/$1 break;
    proxy_pass $upstream_api_qbt;
    proxy_set_header Host qbittorrent;
    proxy_set_header Referer http://qbittorrent:8081;
    proxy_set_header Origin http://qbittorrent:8081;
}

# Sonarr
location /api/sonarr/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_sonarr http://sonarr:8989;
    rewrite ^/api/sonarr/(.*)$ /api/v3/$1 break;
    proxy_pass $upstream_api_sonarr;
    proxy_set_header X-Api-Key {{SONARR_KEY}};
}

# Sonarr Anime
location /api/sonarr-anime/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_sonarr_anime http://sonarr-anime:8989;
    rewrite ^/api/sonarr-anime/(.*)$ /api/v3/$1 break;
    proxy_pass $upstream_api_sonarr_anime;
    proxy_set_header X-Api-Key {{SONARR_ANIME_KEY}};
}

# Radarr
location /api/radarr/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_radarr http://radarr:7878;
    rewrite ^/api/radarr/(.*)$ /api/v3/$1 break;
    proxy_pass $upstream_api_radarr;
    proxy_set_header X-Api-Key {{RADARR_KEY}};
}

# Jellyfin
location /api/jellyfin/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_jellyfin http://jellyfin:8096;
    rewrite ^/api/jellyfin/(.*)$ /$1 break;
    proxy_pass $upstream_api_jellyfin;
    proxy_set_header X-Emby-Token {{JELLYFIN_API_KEY}};
}

# Jellyseerr
location /api/jellyseerr/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_jellyseerr http://jellyseerr:5055;
    rewrite ^/api/jellyseerr/(.*)$ /api/v1/$1 break;
    proxy_pass $upstream_api_jellyseerr;
    proxy_set_header X-Api-Key {{JELLYSEERR_KEY}};
}

# SABnzbd (key in query param)
location /api/sabnzbd/ {
    limit_req zone=api burst=50 nodelay;
    set $upstream_api_sabnzbd http://sabnzbd:8080;
    proxy_pass $upstream_api_sabnzbd/api?apikey={{SABNZBD_KEY}}&$args;
}
