# Auto-generated by setup.sh from templates/nginx.conf.tpl.
# Runs as your user from launchd; paths are relative to the nginx prefix
# (~/media/config/nginx).
worker_processes 1;
pid nginx.pid;
error_log stderr;

events {
    worker_connections 1024;
}

http {
    include {{NGINX_MIME_TYPES}};
    access_log off;

    client_body_temp_path temp/client_body;
    proxy_temp_path temp/proxy;
    fastcgi_temp_path temp/fastcgi;
    uwsgi_temp_path temp/uwsgi;
    scgi_temp_path temp/scgi;

    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    # Default max upload size (override per-server as needed)
    client_max_body_size 50m;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # Hide server version
    server_tokens off;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml text/javascript;
    gzip_proxied any;
    gzip_min_length 256;

    # Rate limiting for API endpoints
    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;
    limit_req_status 429;

    # WebSocket support
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    # Shared proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    # Dashboard
    server {
        listen {{DASHBOARD_PORT}} default_server;
        server_name _;

        root www;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # API proxy endpoints (keys injected by setup.sh)
        # Rate limiting (zone=api) is applied inside api-proxy.conf locations
        include api-proxy.conf;

        # Only the read-only endpoints listed in api-proxy.conf are exposed
        location /api/ {
            return 404;
        }

        # Friendly error page when a backend is down
        error_page 502 503 504 /50x.html;
        location = /50x.html {
            default_type text/html;
            return 502 '<!DOCTYPE html><html><head><title>Service Unavailable</title>
            <style>body{background:#0f0f1a;color:#e0e0e0;font-family:system-ui;display:flex;justify-content:center;align-items:center;height:100vh;margin:0}
            .msg{text-align:center}.msg h1{color:#e94560;font-size:2rem}.msg p{color:#7a7a9a;margin-top:0.5rem}</style></head>
            <body><div class="msg"><h1>Service Unavailable</h1><p>The backend service is starting up or unreachable. Try again in a moment.</p></div></body></html>';
        }
    }
}
