"""Unpackerr extracts archived downloads so Sonarr/Radarr can import them;
its config points it at both apps (with their API keys)."""
from __future__ import annotations

from mediaserver import common as c
from mediaserver import launchd
from mediaserver.config import Config, Keys
from mediaserver.ui import info, ok


def render(cfg: Config, keys: Keys) -> str:
    downloads = cfg.paths.downloads
    return f'''## Unpackerr — auto-generated by setup.sh

[[sonarr]]
url = "http://localhost:8989"
api_key = "{keys.sonarr}"
paths = ["{downloads}"]

[[radarr]]
url = "http://localhost:7878"
api_key = "{keys.radarr}"
paths = ["{downloads}"]
'''


def run(cfg: Config) -> None:
    info("Writing Unpackerr config...")
    conf = cfg.paths.config / "unpackerr/unpackerr.conf"
    new = render(cfg, Keys.read(cfg.paths.config))
    # It holds the Sonarr/Radarr API keys
    if c.read_text(conf) == new.strip():
        conf.chmod(0o600)
        ok("Config unchanged")
        return
    c.write_atomic(conf, new, mode=0o600)
    ok("Config written")
    if launchd.restart(cfg.paths.config, "unpackerr"):
        ok("Unpackerr restarted with new config")
